version: "3"

services:
  frontend:
    build:
      context: "frontend/"
    image: creekmore.io
    # env_file:
    #   - "./vue/.env"
    ports:
      - 3001:3000

  # backend:
  #   build: ./backend
  #   image: mattcreekmore/backend
  #   volumes:
  #     - ./backend:/data
  #   depends_on:
  #     - mongo
  #   ports:
  #     - "3000:3000"
  #   expose:
  #     - "3000"
  #   environment:
  #     - DATABASE_URL=mongo:27017
