version: "3"

services:
  client:
    build: ./frontend
    image: mattcreekmore/client
    #environment:
    #  - VUE_APP_API_URL=server:3000
    ports:
      - 8081:80
    expose:
      - "8080"
    volumes:
      - ./frontend:/data
      # new
      #- ./frontend:/app
      #- ./frontend/node_modules/app/node_modules
    depends_on:
      - nginx

  nginx:
    build: ./nginx
    links:
      - server
    ports:
      - "80:80"
      - "443:443"
      - "3000:3000"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    command: [nginx-debug, "-g", "daemon off;"]

  server:
    build: ./backend
    image: mattcreekmore/server
    volumes:
      - ./backend:/data
    depends_on:
      - mongo
    environment:
      - DATABASE_URL=server-database:27017

  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
