version: "3"

services:
  client:
    environment:
      - VUE_APP_API_URL="server:3000"
    build: ./frontend
    ports:
      - 80:80
    volumes:
      - ./frontend:/data
    depends_on:
      - server
    network_mode: host

  server:
    build: ./backend
    ports:
      - 3000:3000
    expose:
      - "3000"
    volumes:
      - ./backend:/data
    depends_on:
      - mongo
    environment:
      - DATABASE_URL=server-database:27017

  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
